---
- name: Add docker repository
  get_url:
    url: "{{ docker_repo }}"
    dest: "{{ repos_path }}/{{ docker_edition }}.repo"

- name: Install docker
  yum:
    name: "{{ docker_edition }}"
    state: "{{ docker_package_state }}"
  notify: Restart docker
